fix: Run release verification with `--profile=ci` (#20987)
## Which issue does this PR close?

- Related to https://github.com/apache/datafusion/issues/20689
- Closes https://github.com/apache/datafusion/issues/20992
- part of https://github.com/apache/datafusion/issues/19692


## Rationale for this change

While verifying DataFusion 53.0.0, we found that the
`verify_release_candidate` script was not working correctly, as it was
hitting an assertion

Specifically:

```shell
$ ./dev/release/verify-release-candidate.sh 53.0.0 2
...
    joins::sort_merge_join::tests::test_should_emit_early_when_have_enough_data_to_emit

test result: FAILED. 1190 passed; 78 failed; 0 ignored; 0 measured; 0 filtered out; finished in 8.89s

error: test failed, to rerun pass `-p datafusion-physical-plan --lib`
+ cleanup
+ '[' no = yes ']'
+ echo 'Failed to verify release candidate. See /var/folders/1l/tg68jc6550gg8xqf1hr4mlwr0000gn/T/datafusion-53.0.0.XXXXX.d5aUZcsu7v for details.'
Failed to verify release candidate. See /var/folders/1l/tg68jc6550gg8xqf1hr4mlwr0000gn/T/datafusion-53.0.0.XXXXX.d5aUZcsu7v for details.
```

The failure is due to an overzealous assert in arrow-rs (see
https://github.com/apache/arrow-rs/issues/9506) that will be fixed in
the next release

The reason this isn' triggered on CI is that sqllogictests are run with
`--profile=ci` -- see

https://github.com/apache/datafusion/blob/11b9693952cd419b73dd03cc39f22c8b343bc05c/.github/workflows/rust.yml#L299-L298

## What changes are included in this PR?

1. Update verify_release.sh to use `--profile=ci` when running
sqllogictests to mirror CI

## Are these changes tested?

I tested it manually (STILLRUNNING)

```shell
$ ./dev/release/verify-release-candidate.sh 53.0.0 2
...
/var/folders/1l/tg68jc6550gg8xqf1hr4mlwr0000gn/T/datafusion-53.0.0.XXXXX.j0FgM9yH5J
+ TEST_SUCCESS=yes
+ echo 'Release candidate looks good!'
Release candidate looks good!
+ exit 0
+ cleanup
+ '[' yes = yes ']'
+ rm -fr /var/folders/1l/tg68jc6550gg8xqf1hr4mlwr0000gn/T/datafusion-53.0.0.XXXXX.j0FgM9yH5J
```

## Are there any user-facing changes?
No